init app
monireh-sanaei/forum-app pull request #1
Opened 2021-11-15 11:41 UTC by monireh-sanaei

2021-11-15 21:52 UTC, samAZI requested changes
Merci pour cette pull request Monireh 🙏 

Pour commencer j'ai trouvé quelques fichiers & dossiers qui ne sont pas nécessaire au projet pour différentes raisons. J'ai donc essayé de détailler point par point. Dis moi si tu as besoin de plus d'explications.

`npm start ` ne se lance pas, mais en faisant `node app.js` j'ai réussit à lancer le bon serveur. J'ai pu affiché le hello-world 🎉 

Pour valider le ticket il faut qu'il remplisse tous les critères d'acceptances. Si tu regardes la checklist il fallait installer `eslint` et `prettier`, tu sais ce qu'il reste à faire 💪

2021-11-15 21:52 UTC, samAZI commented on bin/www
> +}
Ce fichier fait doublon avec le `app.js` car les 2 sont des serveurs. 
Un utilisant comme librairie `express` et l'autre `http`.

2021-11-15 21:52 UTC, samAZI commented on bin/www
> +}
Je te conseillerai de supprimer celui-ci.
Ainsi que de désinstaller les modules que tu n'utilises plus (voir ceux utiliser dans ce fichier)

2021-11-15 21:52 UTC, samAZI commented on package.json
> +    "pug": "2.0.0-beta11"
Après avoir supprimé le fichier `bin/www.js` tu pourras conserver seulement express dans cette liste. Car les autres ne seront plus appelés dans le code.

2021-11-15 21:52 UTC, samAZI commented on package.json
> +    "@types/express": "^4.17.13"
Ce module est utilisé en typescript. Il permet d'avoir accès aux types fournit par la librairie express.
Ici tu es en full JS donc tu n'as pas besoin d'installer ce module. Tu peux le désinstaller

2021-11-15 21:52 UTC, samAZI commented on public/stylesheets/style.css
> +}
Pourquoi du css coté serveur ? Tu peux supprimer

2021-11-15 21:52 UTC, samAZI commented on routes/index.js
> +module.exports = router;
Ce fichier n'est pas utilisé par ton app.js (à la racine)
Ce n'est pas nécessaire pour le moment [YAGNI](https://fr.wikipedia.org/wiki/YAGNI)

2021-11-15 21:52 UTC, samAZI commented on routes/users.js
> +module.exports = router;
Pas nécessaire YAGNI

2021-11-15 21:52 UTC, samAZI commented on views/error.pug
> +  pre #{error.stack}
Pas de html / pug coté serveur. A supprimer

2021-11-15 21:52 UTC, samAZI commented on views/index.pug
> +  p Welcome to #{title}
Pas de html / pug coté serveur. A supprimer

2021-11-15 21:52 UTC, samAZI commented on views/layout.pug
> +    block content
Pas de html / pug coté serveur. A supprimer

2021-11-15 21:52 UTC, samAZI commented on package.json
> +    "start": "node ./bin/www"
Tu peux remplacer ce script pour qu'il utilise le bon fichier _app.js_ ?

2021-11-17 15:04 UTC, monireh-sanaei commented on bin/www
> +}
Done!

2021-11-17 15:07 UTC, monireh-sanaei commented on package.json
> +    "@types/express": "^4.17.13"
Ok!

2021-11-18 12:33 UTC, samAZI approved these changes
Il manque quelques petites trucs pour que la PR soit complète. Mais je te la valide pour te débloquer et avancer sur le reste car c'est non-bloquant.

2021-11-18 14:29 UTC, merged